### ISSUE TITLE
Secret is sent to user

### ISSUE THREAD

**Issue by domlat** [blockchain/receive-payments-demos#10]
I installed this demo.  Using Firebug I looked at what was being sent to the user's browser. And here it is (in redacted and expanded form):

{"input_address":"1CuUmZkeS--------DsLesY87qV9JZc3iR",
"callback_url":"http:\/\/domain.com\/blockchain_php_demo
\/callback.php?invoice_id=

&secret=this_is_the_secret_I_chose",   <==== LOOOK!!!!!!!

"fee_percent":0,
"destination":"1FTM7Z6xjkV--------yBt583d1wqqV5A"}

I really hope nobody has used this demo code as the basis for a production site!

**Comment by pdpi** [comment]
Resolved in newer versions. Closing.
