### ISSUE TITLE
Error Input String May Contain HTML

### ISSUE THREAD

**Issue by josecelano** [blockchain/receive-payments-demos#14]
I am doing a test with this callback url:

http://example.com/callback?payment_address_id=1&token=VUoIYPH_JdzBwcyvNrcL9aHIpBKGhm-zuTYrL0mL91Q

in https://blockchain.info/api/api_receive

and I get the message: "Error Input String May Contain HTML"

If I remove the "-" or simply I change its position the error disappear.

**Comment by pdpi** [comment]
Inactive. Closing.
