### ISSUE TITLE
2 issues on index.php

### ISSUE THREAD

**Issue by farhadfx** [blockchain/receive-payments-demos#17]
Hello,

1. <?php echo $blockchain_root ?>Resources/buttons/pay_now_64.png
This button does not exists (anymore)

2. <div class="blockchain stage-paid">
                Payment Received <b>[[value]] BTC</b>. Thank You.
            </div>
does not work. This stage never meets although callback.php returns OK .

Please advise.

**Comment by pdpi** [comment]
Fixed in v2 version.
