### ISSUE TITLE
Ask for help, Error Forwarding destination address cannot be the target of another forwarding

### ISSUE THREAD

**Issue by chenzhongdezhanghu** [blockchain/receive-payments-demos#23]
<?php 
$secret = 'ZzsMLGKe162CfA5EcG6j';

$my_address = '1PdDniuvQjddjzooZpRKR4h5rMjUWc5BdU';

$my_callback_url = 'http://buy.sff3.com/btcapi/callback.php';

$root_url = 'https://blockchain.info/api/receive';

$parameters = 'method=create&address=' . $my_address . '&callback='. urlencode($my_callback_url);

$response = file_get_contents($root_url . '?' . $parameters);

$object = json_decode($response);

echo 'Send Payment To : ' . $object->input_address;
?>

**Comment by pdpi** [comment]
Inactive and not enough information to act on. Closing.
