### ISSUE TITLE
Server Did Not Respond With *ok* : Invalid Secret

### ISSUE THREAD

**Issue by Meinsss** [blockchain/receive-payments-demos#24]
Visiting this website (https://blockchain.info/de/api/api_receive) and under Call The API I'm typing in my BTC Adress and URL to the Callback.php
Everytime I get an "Server Did Not Respond With _ok_ : Invalid Secret" error.
It doesn't matter to what I'm editing my secret, wheter the standard on this site or something else, it stays so.
Hope that you can help me

**Comment by pdpi** [comment]
Hi @Meinsss. Is this still an ongoing issue for you?

**Comment by PhamDiesel** [comment]
mission to build a more open, accessible, and fair financial future, one piece of software at a time. no
