### ISSUE TITLE
Always Payment not received..

### ISSUE THREAD

**Issue by danilomoretto** [blockchain/receive-payments-demos#3]
Hi, congratulations for this good work.
I´m writing to ask, i recently testing the receive_payment_php_demo i saw it in bloackchain.

I put it in my PC, inside /var/www/ (linux debian) doing a git clone, i´ve setup a dyndns account to manage a domain name, change the name of directory from /var/www/receive_payment_php_demo to other name, short, chmod -R 755 the directory, so i write my conf in the includes.php, run the setup.php in the browser and check it in mysql, all fine.

After that try myDomainName/pathToReceive_payment_php_demo/

show the invoice, i make the transfer for the $0.15 example, (from other wallet) and receive it in my wallet in blockchain.. but appear "payment not received" i see in blockchain and have more than 4 confirmations...

is there other conf tha i missed? 
please Excuse my poor English

Very thanks. waiting for some help

Danilo

**Comment by ClericPreston** [comment]
Demo is not working!

All time = "payment not received"

**Comment by Meinsss** [comment]
Hey there.
changed the code as you said, but still getting this error after 3 confirmations of the sent amound and 2 of the received amount.
<img width="264" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/15094202/10435613/5845f1ec-7121-11e5-8fa7-0ec14af24105.PNG">

**Comment by tuzzolo** [comment]
Hi @Meinsss. Please upgrade your implementation to our new v2 API. Documentation can be found here: https://blockchain.info/api/api_receive

**Comment by PhamDiesel** [comment]
mission to build a more open, accessible, and fair financial future, one piece of software at a time.
