### ISSUE TITLE
create.php

### ISSUE THREAD

**Issue by mthosting** [blockchain/receive-payments-demos#4]
create.php still reveals the callback URL it is just masked better. I used the follow modification in my implementation of your code.

$response = json_decode(file_get_contents($blockchain_root . "api/receive?method=create&callback=" . urlencode($callbackURL) . "&address=" . $GATEWAY["bitcoin_addr"]));
print json_encode(array('input_address' => $response->input_address ));

**Comment by pdpi** [comment]
Resolved.
