### ISSUE TITLE
qr image address in pay-now-button-v2.js

### ISSUE THREAD

**Issue by rawthriver** [blockchain/receive-payments-demos#42]
There is a definition in pay-now-button-v2.js file:
var root = "/web/20160528015731/https://blockchain.info/";

So qr-code image receives src starting with "/web/20160528015731/" and could not be loaded.
When I remove "/web/20160528015731/" image does appear.

**Comment by assafY** [comment]
Thanks @rawthriver 

This will be fixed shortly
