### ISSUE TITLE
Who did pay? Hack? https://api.blockchain.info/v2/receive/balance_update

### ISSUE THREAD

**Issue by almaz1213** [blockchain/receive-payments-demos#45]
Hi,

concerning https://api.blockchain.info/v2/receive/balance_update.

If I am monitoring my addr to detect receive confirmation of some invoice, how to detect that received funds to the addr were sent from expected customer? because, anyone can send funds to my addr for the period.

**Comment by almaz1213** [comment]
it can cause hacking services that use your payment APIs

**Comment by assafY** [comment]
Hi,

The intended use is to generate a new address for every customer using the API. Ideally, your service will also provide a slightly different callback for every customer, e.g. `https://mystore.com?invoice_id=058921123`.

**Comment by almaz1213** [comment]
it is clear. but what if someone pay to the addr at the same time? how my backend can detect an exact payer?

**Comment by assafY** [comment]
There is no way to get a callback from payment from a specific address, nor should your backend expect a payment from a specific address -  rather you should generate and display a new address for every customer, therefore eliminating the possibility of receiving more than one payment for a single address.

Your backend should detect an exact payer by having the callback include payer-specific information, such as the order id.

**Comment by assafY** [comment]
I am closing this as there is no issue to resolve here, but please let me know if you have any more questions.

**Comment by almaz1213** [comment]
what if payer send funds several times to the generated addr and with different amounts?

**Comment by almaz1213** [comment]
callback_url is fired anyway when some one sends to the addr any btc amount, independence what addr did send, right?

**Comment by assafY** [comment]
That's correct. Therefore you will receive a notification for every payment received at that address.

**Comment by almaz1213** [comment]
so, what if every payment was payed from different addresses?

**Comment by assafY** [comment]
The API does not return information regarding the address a payment was received from, as that should not really matter. If you want to know explicitly what addresses sent funds to an address, you can use our other APIs. For instance,

```
https://blockchain.info/rawaddr/{address}
```

will return all transactions for the address provided.

**Comment by almaz1213** [comment]
i have told about that it's usable for hack your API users..

**Comment by assafY** [comment]
Would you care to explain again how?

**Comment by almaz1213** [comment]
i will..

**Comment by almaz1213** [comment]
is there way to test the API without real payments?

**Comment by almaz1213** [comment]
what if N (N>20) customers begin to pay on our website within short time (for example, 20 minutes) and we generate new addresses for them using https://api.blockchain.info/v2/receive, but the first 20 of them didn't finish payment yet? Does it mean that gap go over 20 and 21st user cannot have an addr for payment because of "this API will return an error and refuse to generate new addresses if it detects it would create a gap of over 20 unused addresses" (from your API docs)?
