### ISSUE TITLE
Gap in https://api.blockchain.info/v2/receive

### ISSUE THREAD

**Issue by almaz1213** [blockchain/receive-payments-demos#46]
what if N (N>20) customers begin to pay on our website within short time (for example, 20 minutes) and we generate new addresses for them using https://api.blockchain.info/v2/receive, but the first 20 of them didn't finish payment yet? Does it mean that gap go over 20 and 21st user cannot have an addr for payment because of "this API will return an error and refuse to generate new addresses if it detects it would create a gap of over 20 unused addresses" (from your API docs)?

**Comment by assafY** [comment]
If you expect to generate more than the default amount of addresses before payments are received (20) you can set the gap_limit parameter to a higher number when making the call to generate an address.
