### ISSUE TITLE
MSYQLI Issues On Order Status Page

### ISSUE THREAD

**Issue by michaelsomerville** [blockchain/receive-payments-demos#51]
Anyone else have issues with the MYSQLI calls ??

Example

`Fatal error: Call to undefined method mysqli_stmt::get_result() in /...../order_status.php on line 23`

Can't seem to figure any of this out, not only that it doesn't seem to use the callback ever.

**Comment by assafY** [comment]
Hi again,

As you recently posted about a callback not being sent more than once, is this still an issue for you?

**Comment by michaelsomerville** [comment]
Yes

**Comment by PhamDiesel** [comment]
mission to build a more open, accessible, and fair financial future, one piece of software at a time.
