### ISSUE TITLE
Callback only once ?

### ISSUE THREAD

**Issue by michaelsomerville** [blockchain/receive-payments-demos#52]
Hey Guys!
Anyone else ever have an issue where the callback was only ever hit once ? I mean it's sit up fine, hits it ....

```
[ {
  "callback" : "http://XXXX.com/apitesting/bc-api/callback.php?invoice_id=22&secret=XXXX",
  "calledAt" : 1510207257000,
  "responseCode" : 200,
  "rawResponse" : "Waiting for confirmations"
} ]
```

And that's it - never comes back to tell me how many confirmations or anything. Thoughts ?

**Comment by assafY** [comment]
Hi,

Can you post the response your server returns when the callback is received?

**Comment by michaelsomerville** [comment]
I didn't that's what it shows above in my comment.

**Comment by michaelsomerville** [comment]
It sends the first time, then logs what I have above ...

```
[ {
  "callback" : "http://XXXX.com/apitesting/bc-api/callback.php?invoice_id=22&secret=XXXX",
  "calledAt" : 1510207257000,
  "responseCode" : 200,
  "rawResponse" : "Waiting for confirmations"
} ]
```
Everything is prefect on my end, when I test and debug. The api callback never sends or comes to the url again after that. There is no " *OK* " shown and you can see that from the log I pasted here.

I have a logger on the file to track if the server sends again, but never does.

**Comment by assafY** [comment]
Can you try to respond to the callback with plain text `*ok*`?

**Comment by assafY** [comment]
This is not an issue any longer.
