### ISSUE TITLE
BUG REPORT: Gap limit is not counted correctly 

### ISSUE THREAD

**Issue by leonar15** [blockchain/receive-payments-demos#61]
Hi,
I'm seeing an issue where calls to the /v2/receive API are reaching the gap limit even though there are incoming payments to most or all of the generated addresses. I believe a recent change broke how the gap limit is counted and this means that all xpubs became limited to 20 **total** transactions. 

Any help/feedback would be appreciated.

**Comment by assafY** [comment]
Hi @leonar15 

Thank you for bringing this up. I have just tested this, and on my end the gap limit parameter does work in increasing the max allowed unpaid addresses. However, the parameter must be set for every address request after the default limit of 20 was reached.

Can you please let me know whether this problem occurs when you reach the default gap limit, and then include the gap limit parameter with a higher value in your request?

**Comment by leonar15** [comment]
Thanks for the reply. I opened a support ticket regarding this issue about a week ago and it looks like it was resolved over the past couple of days. 

For the record, I was not passing the "gap limit" parameter, but the /v2/receive/checkgap call was returning
`{
  "gap" : 21
}`
even though there were only 21 total incoming addresses created and they had all been used.

Other xpubs are now returning the expected gap value of 0 or 1.

**Comment by assafY** [comment]
Right, thank you for clarifying. I am glad the issue is fixed, it must have been related to other issues we had with callbacks over the last few days.

**Comment by PhamDiesel** [comment]
mission to build a more open, accessible, and fair financial future, one piece of software at a time.

**Comment by PhamDiesel** [comment]
mission to build a more open, accessible, and fair financial future, one piece of software at a time.
